#!/usr/bin/env bash

MODULE_NAME="hyprlock"
MODULE_VERSION="2.0.0"

MODULE_DESCRIPTION="Hyprlock lock screen"

MODULE_AUTHOR="Suyash"

MODULE_CONFIG_DIR="$HYPRLOCK_DIR"

MODULE_REQUIRED=true
MODULE_ENABLED=true

MODULE_THEMEABLE=true
MODULE_RELOADABLE=false
