#!/usr/bin/env bash

MODULE_NAME="swaync"
MODULE_VERSION="1.0.0"
MODULE_DESCRIPTION="swaync"

MODULE_AUTHOR="Suyash"

MODULE_CONFIG_DIR="$SWAYNC_DIR"

MODULE_REQUIRED=false
MODULE_ENABLED=true

MODULE_THEMEABLE=true
MODULE_RELOADABLE=true
