source = ~/.config/hyprlock/colors.conf

source = ~/.config/hyprlock/widgets/background.conf
source = ~/.config/hyprlock/widgets/clock.conf
source = ~/.config/hyprlock/widgets/date.conf
source = ~/.config/hyprlock/widgets/username.conf
source = ~/.config/hyprlock/widgets/media.conf
source = ~/.config/hyprlock/widgets/password.conf
source = ~/.config/hyprlock/widgets/greeting.conf
