general {
    disable_loading_bar = true
    hide_cursor = false
}

background {
    monitor =
    path = screenshot

    blur_passes = 6
    blur_size = 12

    brightness = 0.75
    contrast = 1.12

    noise = 0.010

    vibrancy = 0.16
}