label {
    monitor =

    text = cmd[update:60000] echo "$(date +'%A, %d %B %Y')"

    color = $foreground

    font_size = 20
    font_family = JetBrainsMono Nerd Font

    position = 0, 105

    halign = center
    valign = center
}
