label {
    monitor =

    text = राम राम, सुयश ब्राह्मण जी

    color = $orange

    font_size = 26
    font_family = Noto Sans Devanagari

    position = 0, -185

    halign = center
    valign = center
}
