label {
    monitor =

    text = cmd[update:1000] ~/.config/hypr/scripts/lockscreen-music.sh

    color = $green

    font_size = 18
    font_family = JetBrainsMono Nerd Font

    position = 0, -20

    halign = center
    valign = center
}
