input-field {
    monitor =

    size = 360, 56

    outline_thickness = 2

    outer_color = $accent
    inner_color = rgba(20,20,20,0.35)

    font_color = $foreground

    check_color = $green
    fail_color = $red

    fade_on_empty = false

    rounding = 24

    placeholder_text = Password

    dots_size = 0.25
    dots_spacing = 0.30
    dots_center = true

    shadow_passes = 2
    shadow_size = 4

    position = 0, -90

    halign = center
    valign = center
}