#!/usr/bin/env bash

MODULE_NAME="waybar"
MODULE_VERSION="2.0.0"

MODULE_DESCRIPTION="Waybar status bar"

MODULE_AUTHOR="Suyash"

MODULE_CONFIG_DIR="$WAYBAR_DIR"

MODULE_REQUIRED=true
MODULE_ENABLED=true

MODULE_THEMEABLE=true
MODULE_RELOADABLE=true
